### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by tarsisferreira** [bowman-lab/diffnets#6]
Hi I encountered this assertion error while running the tests. Is it something that can be fixed?

/lab/diffnets/diffnets/data_processing.py:406: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180511146/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:2499.)
  e, v = torch.symeig(torch.from_numpy(c00).double(), eigenvectors=True)
Traceback (most recent call last):
  File "/home/lab/diff/diffnets/diffnets/cli/main.py", line 325, in <module>
    cli()
  File "/home/lab/anaconda3/envs/diffnets/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lab/anaconda3/envs/diffnets/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lab/anaconda3/envs/diffnets/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lab/anaconda3/envs/diffnets/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lab/anaconda3/envs/diffnets/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lab/diff/diffnets/diffnets/cli/main.py", line 124, in preprocess_data
    whiten_traj.run()
  File "/home/lab/diff/diffnets/diffnets/data_processing.py", line 530, in run
    uwm, wm = self.get_wuw_mats(c00)
  File "/home/lab/diff/diffnets/diffnets/data_processing.py", line 410, in get_wuw_mats
    assert torch.min(e) > 0.0
AssertionError
Thanks for using enspara! Please read and cite the folllowing articles:
{'title': 'Enspara: Modeling molecular ensembles with scalable data structures and parallel computing', 'authors': ['Porter Justin, R', 'Zimmerman, Maxwell I', 'Bowman, Gregory R'], 'journal': 'JCP', 'year': 2019, 'doi': '10.1063/1.5063794@jcp.2019.MMMK.issue-1'}

**Comment by Hendejac** [comment]
I am also receiving the exact same error.
